config/routes.rb
Rails.application.routes.draw do

  get 'search' => 'movies#search'
  get 'search_series' => 'series#search'
  get 'home/index'
  get 'home/about'
  get 'reviews/all' => 'reviews#index'
  get 'home/index'
  get 'users/:id/change_password' => 'users#password'
  resources :movies
  resources :reviews ,path: 'movies/:id/reviews'
  resources :series
  resources :users

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

   root 'movies#index'

    get '/404' => 'errors#not_found'
    get '/422' => 'errors#internal_error'
    get '/500' => 'errors#unprocessable_entity'

end

app/controllers/movies_controller.rb
require 'net/http'
require 'json'
require 'uri'
require 'enumerator'
class MoviesController < ApplicationController
  attr_accessor :sort_key
  def index
    @movie_service = MovieService.new
  end
  def search
    @name = params[:search]
  end
  def show
    @review = Review.new
    @movie = singleMovie
  end
  def destroy
    review = Review.find(params[:id])
    review.destroy
    redirect_to movies_path
  end
  private
  def singleMovie
    @movie_service = MovieService.new
    @movie_service.single_movie(params[:id].to_s, true)
  end
end

app/helpers/movies_helper.rb
require "net/http"
require "uri"

module MoviesHelper
  def search(movies , sort_key = 'imdbID')
    movies = movies.to_s.gsub('"', ' ').gsub('<', ' ').gsub('>', ' ').gsub(';', ' ').gsub('/', ' ')
    searcher = movie_service.search_movies(movies.to_s)
    if exists?(searcher) == true
         searcher = searcher["Search"]
          searcher = searcher.uniq{|m| m["imdbID"]}
          searcher = searcher.sort_by{|n| n["#{sort_key}"]}
          # searcher = searcher.select{|movie|  is_good_movie?(movie)}
    else
      searcher = false
    end
    searcher
  end
  def single_search(movie , idOn = false)
    @movie = movie_service.single_movie(movie, idOn)
 end
   def single_poster(poster, no_check=false, mac = false)
      if mac == true
        poster = poster["Poster"]
          if poster != 'N/A'
           poster = "#{poster.to_s}"
          else
            poster = 'noposter.jpg'
          end
          poster
      else
          poster = movie_service.omdb_poster(poster, no_check)
           if poster != 'N/A'
           poster = "#{poster.to_s}"
          else
            poster = 'noposter.jpg'
          end
          poster
        end
  end
  private

  def exists? (search)
    puts search.size
    puts 'Banana'
    if search.size == 2
      false
    else
      true
    end
  end
  def is_good_movie?(movie)
    movie = single_search(movie)
    ((movie["imdbRating"].to_i > 4) &&  (movie["Rated"] != 'N/A'))
  end

  private
  def movie_service
    MovieService.new
  end
  def searcher_params
    params.require(:searcher).permit(:search_input)
  end
end

app/views/movies/_reviews.html.erb
<div>
<% if  Review.where(movie_id: "#{id}") == nil %>
<% else %>
    <% reviews = Review.where(movie_id: "#{id}") %>
    <% reviews.reverse_each do |review| %>
            <div class="panel panel-default">
                <div class="panel-heading"><%= review.title %></div>
                <div class="panel-body"><%= review.body%></div>
                <div class="panel-heading">
                      <footer>
                            <span><%= "Created: #{format_review_date(review)}" %></span>
                            <% if current_user != nil %>
                                <% if current_user.level == 3 %>
                                        <span>   |   <%= link_to "Delete Review", review_path(params[:id] , review), method: :delete, data: {confirm: "Are you sure you want to delete this review? "} %> </span>
                                <% end %>
                            <% end %>
                      </footer>
                </div>
            </div>
    <%end%>
<% end %>
</div>

app/views/movies/_searcher.html.erb
<%= form_tag("/search", method: "get") do %>
  <%= label_tag(:q, "Search for:") %>
  <%= text_field_tag(:q) %>
  <%= submit_tag nil, :class => 'btn btn-warning' %>
<% end %>

app/views/movies/index.html.erb
<h1>Movies</h1>
<h3>These are the featured movies: </h3>

<% results = [single_search('tt0316654', true), single_search('tt0478970', true),single_search('tt0848228', true) ,single_search('tt0092086', true), single_search('tt0113243', true), single_search('tt3416742', true)]%>
<% if results != false%>
    <% results = results.sort_by{|n| n[params[:sort_key]]} %>
    <% results.each do |r| %>
    <% r = single_search(r) %>
    <div class = 'col-xs-6 col-lg-4'><h4><%= link_to("#{r["Title"]} ( #{r["Year"]} )".truncate(23), "/movies/"+(r["imdbID"]).to_s)%></h4>
    <div style="height: 350px;"><%= link_to(image_tag(single_poster(r, true), :alt => "#{r['Title']} movie poster",:width => "200", :class =>"thumbnail"),  "/movies/"+(r["imdbID"]).to_s) %> </div>
    </div>
    <% end %>
<% else %>

<p>No movies exist with that name... Soz </p>
<% end  %>

app/views/movies/search.html.erb
<div><h1></h1></div>
<div><h4>Search term was : <%= @name.gsub('+',' ') %></h4></div>
<div><h1></h1></div>
<% movies_results = search(@name.gsub('+',' '), params[:sort_key])%>
<% series_results = series_search(@name.gsub('+',' '), params[:sort_key] , 10)%>
<% if movies_results != false || series_results != false%>
    <h3 class = "col-xs-12"> Movies </h3>
    <% if movies_results != false %>

        <% movies_results.each do |r| %>
        <% r = single_search(r) %>
        <div class = 'col-xs-6 col-lg-4'><h4><%= link_to("#{r["Title"]} ( #{r["Year"]} )".truncate(23), "/movies/"+(r["imdbID"]).to_s)%></h4>
        <div style="height: 350px;"><%= link_to(image_tag(single_poster(r), :alt => "#{r['Title']} movie poster",:width => "200", :class =>"thumbnail"),  "/movies/"+(r["imdbID"]).to_s) %> </div>
        </div>

        <% end %>
    <% else  %>
     <div class= "col-xs-12">  No Movies with that name </div>
    <div class= "col-xs-12"> <%= image_tag("sHvEPkW.gif", :class => 'img-rounded thumbnail img-responsive') %></div>
    <% end %>
    <h3 class = "col-xs-12"> Series </h3>
       <% if series_results != false %>
    <% series_results.each do |r| %>

        <% r = series_search(r['imdbID']) %>
        <div class = 'col-xs-6 col-lg-4'>
        <h4><%= link_to("#{r["Title"]} ( #{r["Year"]} )".truncate(23), "/series/"+(r["imdbID"]).to_s)%></h4>
        <div style="height: 350px;"><%=  link_to(image_tag(single_poster(r), :alt => "#{r['Title']} tv-series poster", :width => "200", :class =>"thumbnail"),  "/series/"+(r["imdbID"]).to_s) %> </div>
        </div>
    <% end %>
        <% else  %>
             <div class= "col-xs-12">  No Series with that name </div>
        <div class= "col-xs-12"><%= image_tag("no_series.gif", :class => 'img-rounded img-thumbnail') %></div>
    <% end %>

<% else %>
<p> Something went wrong with that search term... Sorry </p>
<p>Oh well.. At least you get to look at these cute pandas</p>
<div> <%= image_tag("nothing_here.gif", :class => 'img-rounded img-thumbnail') %></div>
<% end  %>

app/views/movies/show.html.erb
 <div class = "container" >
 <div class = 'col-xs-5 pull-right' align= 'right'>
            <%=image_tag(single_poster(@movie), :alt => "#{@movie['Title']} movie poster",:width => "340", :class => 'img-responsive', :style => 'border: 1px solid #000000;')  %>
            <p align= 'center'><%= link_to("More information on IMDB site", "http://www.imdb.com/title/#{@movie['imdbID'].to_s}/", :target=>"_blank")%> </p>
 </div>
<div style = 'margin-right: 20px' class= "col-xs-6 pull-left" align= 'left' >
    <h2 ><%= "#{@movie["Title"]} ( #{@movie['Year']} )" %></h2>
     <h2><%= ( "IMDB Rating : ( #{@movie['imdbRating']} )") %></h2>
          <h2><%= (" Rated : (#{@movie['Rated']} )") %></h2>
    <p></p>

    <div style= 'margin-right: 0px'>
    <p><%= @movie['Plot'] %> </p>
    <p></p>
    <p><%="Director: #{@movie['Director']}"  %> </p>
    <p><%="Actors: #{@movie['Actors']}"  %> </p>
    <p></p>
    <p><%="Genre: #{@movie['Genre']}"  %> </p>
    </div>
</div>


    <div class = 'col-xs-12'><h3><%="Reviews:"  %></h3>
    <% if logged_in? %>
     <%= render partial: '/reviews/forms' , :locals => {:id => params[:id]  , :user_id => current_user.id , :user_name => current_user.name} %>
     <% else %>
     <div > <a class = 'navbar-brand col-xs-12' style = 'background:orange; color:black; margin-bottom:10px; ' href =" <%= login_path %> ">Please Log in to add a review</a>
     <% end %>
        <%= render partial: '/movies/reviews', :locals => {:id => params[:id]} %>
    </div>
    </div>

</div>