config/routes.rb
Rails.application.routes.draw do

  get 'search' => 'movies#search'
  get 'search_series' => 'series#search'
  get 'home/index'
  get 'home/about'
  get 'reviews/all' => 'reviews#index'
  get 'home/index'
  get 'users/:id/change_password' => 'users#password'
  resources :movies
  resources :reviews ,path: 'movies/:id/reviews'
  resources :series
  resources :users

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

   root 'movies#index'

    get '/404' => 'errors#not_found'
    get '/422' => 'errors#internal_error'
    get '/500' => 'errors#unprocessable_entity'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Matts Movies</title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body style = "padding-bottom:200px">

<div class = "container" style="background:darkdarkgrey; padding-bottom:10px; margin-top:10px">
<nav class="navbar navbar-default" style = " padding-bottom: 10px; padding-top: 10px">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href='/movies'>Movies</a>
      <a  class="navbar-brand" href="/series">Series</a>
      <a  class="navbar-brand" href="/reviews/all"> All Reviews</a>
    </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

                <form class="navbar-form navbar-left" action="/search" accept-charset="UTF-8" method="get">
                <div class="form-group" style = 'margin-top:10px'>
                  <div class="pull-left" align="right" style= "padding-right:0px; padding-left:0px"><input type="text" name="search" id="search"  style = 'width:200px;'class="form-control "placeholder="Search"></input></div>
                  <div class="pull-left" style= "padding-right:0px;padding-left:0px"align="left"><button type="submit" name="commit" class="btn btn-info ">Go</button></div>
                  </div>

                </form>

        <ul class="nav navbar-nav">
          <li class="dropdown">
            <a href="#" class="navbar-brand" data-toggle="dropdown" role="button" aria-expanded="false"> Filters <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'Sort By Alphabetical Order', params.merge(:sort_key => 'Title') %></li>
              <li class="divider"></li>
              <li><%= link_to 'Sort By Release Date', params.merge(:sort_key => 'Year') %></li>
            </ul>
        </ul>

      <div class=" navbar-form navbar-right">
            <% if logged_in? %>
                    <a class="navbar-brand" data-method='delete' href='/logout' %>Log out</a>
                  <div class="navbar-brand">|</div>
                    <a class="navbar-brand" href='<%= user_path(current_user) %>' >Profile</a>
            <% else %>
                <a class="navbar-brand" href='/login'>Log In</a>
                <div class="navbar-brand">|</div>
                <a class="navbar-brand" href= '/users/new'>Sign up</a>
            <% end %>
        </div>
    </div>
    <p></p>
  </div>
  </nav>
<% if @current_user != nil %>
<nav>
  <div class="container-fluid">
    <div class="navbar-header">

    <%if @current_user.level == 3 %>
        <p class="navbar-brand"><%=  ('Welcome Admin.'  if  @current_user != nil)%> <%= (link_to'......Not you?', logout_path, method: 'delete' if  @current_user != nil)%></p>
      <% else %>

        <p class="navbar-brand"><%=  (@current_user.name  if  @current_user != nil)%> <%= (link_to'......Not you?', logout_path, method: 'delete' if  @current_user != nil)%></p>
        <% end %>
  </div>
  </div>
</nav>
<% end %>

 <% flash.each do |name, msg| -%>
              <%= content_tag :div, msg, class: name %>
            <% end -%>


<div class="navbar navbar-fixed-bottom"></div>
<%= yield %>

</body>

<body >
</body>
</html>